### ISSUE TITLE
Please document tools needed to verify registry changes

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/EGL-Registry#92]
Could the tools necessary to validate EGL registry changes, as requested in the README.md - for example, running "make validate" in the api/ directory - please be documented?

It would be great if instructions could be given for all of Linux, macOS and Windows.

Thanks.

**Comment by oddhack** [comment]
I think you don't need anything except GNU make and 'jing': https://relaxng.org/jclark/jing.html, although it's hard to be sure since I have a huge amount of related stuff installed to build other GL / EGL / Vulkan stuff.

jing is packaged for major Linux distributions. I have no Mac experience whatsoever, and on Windows 10 I strongly recommend using the Debian WSL rather than native Windows tools. Cygwin probably will work on older Windows versions.

Actually building the headers requires Python 3.5 and some python libraries, which I won't attempt to enumerate here. Eventually we'll publish a docker image which can be used to build all the artifacts for these repos, and direct people to that.

**Comment by oddhack** [comment]
I pushed a small update which attempts to capture the above comments.
